'use strict';
var UFTest = TestCase('UF');
UFTest.prototype.testUnion = function testUnion(){
	 var uf = new bigo.UF(1000);
	 uf.union(1,2);
	 uf.union(2,3);
	 uf.union(4,5);
	 uf.union(6,7);
	 uf.union(4,7);
	 uf.union(8,9);
	 uf.union(10,11);
	 assertTrue(uf.connected(1,1));
	 assertTrue(uf.connected(1,2));
	 assertTrue(uf.connected(2,1));
	 assertTrue(uf.connected(2,3));
	 assertTrue(uf.connected(3,2));
	 assertTrue(uf.connected(1,3));
	 assertTrue(uf.connected(3,1));
	 assertTrue(uf.connected(4,5));
	 assertTrue(uf.connected(5,4));
	 assertTrue(uf.connected(5,6));
	 assertTrue(uf.connected(6,5));
	 assertTrue(uf.connected(4,7));
	 assertTrue(uf.connected(7,4));
	 assertTrue(uf.connected(6,7));
	 assertTrue(uf.connected(7,6));
	 assertTrue(uf.connected(5,7));
	 assertTrue(uf.connected(7,5));
	 assertFalse(uf.connected(7,8));
	 assertFalse(uf.connected(9,10));
};